name: 'Packages Split'

on:
    push:
        branches:
            - main
        tags:
            - '*'

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    packages_split:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    -
                        local_path: 'baser-core'
                        split_repository: 'baser-core'
        steps:
            -   uses: actions/checkout@v2
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@2.1"
                with:
                    tag: ${GITHUB_REF#refs/tags/}
                    package_directory: 'plugins/${{ matrix.package.local_path }}'
                    repository_organization: 'baserproject'
                    repository_name: '${{ matrix.package.split_repository }}'
                    user_name: "ryuring"
                    user_email: "ryuring55@gmail.com"
